[project]
name = "driving-test-booking-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python-headless>=4.11.0.86",
    "pyautogui>=0.9.54",
]
